# Generated by Django 3.2.19 on 2023-06-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='satatus',
            new_name='status',
        ),
    ]
